### ISSUE TITLE
Migrate to the TypeScript SDK

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/cloud-sample-app-js#7]
https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK
https://github.com/Enngage/KenticoCloudModelGeneratorUtility

**Comment by Simply007** [comment]
New branch created:
https://github.com/Kentico/cloud-sample-app-js/tree/migrate_to_typescript_sdk

**Comment by Simply007** [comment]
63010d01fcd5617a9c3fc1b3254a4dcd5e877757
* models created
* delivery client encapsulation created


TODO:
Use client in the sores and rewrite components to use new models

**Comment by ChristopherJennings** [comment]
@Simply007, I noticed you're doing the same thing with the models as I did when I was trying out the TS SDK. For example, in order to make the names translate from `body_copy` to `bodyCopy`. I ended up writing a helper method to blanket map these items instead of having to map them individually. See https://gist.github.com/ChristopherJennings/3086c7225f6b391ecca9feb6bf3affc4 for my implementation. I then used this in the propertyResolver. This is likely something that should just get included in the TS SDK though.

**Comment by petrsvihlik** [comment]
This could be mentioned somewhere in the readme of the TS SDK.

**Comment by ChristopherJennings** [comment]
It kind of is: https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK#property-binding-in-models 

That example notes that the names are all lower case, which is true, but the example also assumes that the code name doesn't include spaces, which typically are there and could be converted using this method.

**Comment by ChristopherJennings** [comment]
This has been added as an issue on the SDK repo: https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK/issues/6

**Comment by ChristopherJennings** [comment]
@Enngage, you're probably right. I guess we'll just have to see was @Simply007 has to say.

**Comment by Simply007** [comment]
Yeap I have used generator and then converted typescript models to javascript syntax. 
Since we agreed to use typescript, I will regenerate models without any modification and it will be sufficient. 
It would be great thet mapping would be done automatically and used @ChristopherJennings modifier, but for now I will use generated code.

Thanks for tips :-)

**Comment by Enngage** [comment]
@Simply007 , the code generator should already do, what Chris mentioned automatically. What you might however do manually is to use proper models instead of 'IContentItem' for modular item properties as Cloud does not provide this link.

**Comment by Simply007** [comment]
New pull request cretated:
* https://github.com/Kentico/cloud-sample-app-js/pull/9
